import React, {Component} from 'react';
import {appStyles, colors} from '../../services';
import {BackIcon} from '../../components';

export const baseURL = '';
export const endPoints = {
  login: 'login',
  courses: 'rooms',
  classes: 'classes',
};
export const routes = {
  auth: 'auth',
  app: 'app',
  splash: 'splash',
  languageSelection: 'languageSelection',
  walkthrough: 'walkthrough',
  signin: 'signin',
  signup: 'signup',
  signupComplete: 'signupComplete',
  authHome: 'authHome',
  resetPassword: 'resetPassword',
  otpLogin: 'otpLogin',
  otpCode: 'otpCode',
  updatePhoneNo: 'updatePhoneNo',
  verifyYourself: 'verifyYourself',
  home: 'home',
  homeLanding: 'homeLanding',
  categories: 'categories',
  filters: 'filters',
  subCategories: 'subCategories',
  productListing: 'productListing',
  filterProducts: 'filterProducts',
  productDetail: 'productDetail',
  covidTest: 'covidTest',
  bloodTest: 'bloodTest',
  selectTimeNDate: 'selectTimeNDate',
  mapTest: 'mapTest',
  bookingSummary: 'bookingSummary',
  swabTest: 'swabTest',
  vipTestMapHome: 'vipTestMapHome',
  downloadReport: 'downloadReport',
  addAddress: 'addAddress',
  quotationRequest: 'quotationRequest',
  quotationRequestDelivery: 'quotationRequestDelivery',
  quotationRequestPayMethod: 'quotationRequestPayMethod',
  uploadPrescription: 'uploadPrescription',
  pharmacies: 'pharmacies',
  pharmacyDetail: 'pharmacyDetail',
  pharmacyProducts: 'pharmacyProducts',
  pharmacyPage: 'pharmacyPage',
  about: 'about',
  wishList: 'wishList',
  prescriptions: 'prescriptions',
  prescriptionDetail: 'prescriptionDetail',
  quotationsProfile: 'quotationsProfile',
  comparisonList: 'comparisonList',
  myOrders: 'myOrders',
  orderDetail: 'orderDetail',
  trackOrder: 'trackOrder',
  cart: 'cart',
  checkOut: 'checkOut',
  checkOutChangeAddress: 'checkOutChangeAddress',
  orderConfirm: 'orderConfirm',
  editProfile: 'editProfile',
  myPoints: 'myPoints',
  viewProducts: 'viewProducts',
  discountProducts: 'discountProducts',
  trackOrderDetail: 'trackOrderDetail',
};
export const storageConst = {
  userData: 'userData',
  userId: 'id',
  language: 'language',
  guest: 'guest',
  guestId: 'guestId',
  paymentID: 'paymentID',
  paymentDone: 'paymentDone',
  firstTime: 'firstTime',
};
export const headers = {
  screenOptions: {
    // headerShown: false,
    title: 'Title',
    headerTitleAlign: 'left',
    headerStyle: [appStyles.headerStyle],
    headerTitleStyle: appStyles.headerTitleStyle,
    headerTintColor: colors.appTextColor4,
    headerBackImage: () => <BackIcon />,
    headerBackTitle: ' ',
  },
};
export const tabs = {
  tabBarOptions: {
    //showLabel: false,
    activeTintColor: colors.appTextColor6,
    inactiveTintColor: colors.appTextColor6,
    allowFontScaling: true,
    style: appStyles.tabBarStyle,
    activeBackgroundColor: '#FFFFFF40',
    tabStyle: {borderRadius: 20, marginHorizontal: 7.5, marginVertical: 2},
  },
  topTabBarOptions: {
    //showLabel: false,
    activeTintColor: colors.appColor1,
    inactiveTintColor: colors.appColor1,
    allowFontScaling: true,
    style: appStyles.searchTopTabBarStyle,
    showIcon: true,
    indicatorStyle: {backgroundColor: colors.appColor1},
    tabStyle: {flexDirection: 'row'},
    labelStyle: [appStyles.textRegular, appStyles.textPrimaryColor],
    // activeBackgroundColor:'#FFFFFF40',
    //tabStyle:{borderRadius:20,marginHorizontal:7.5,marginVertical:2}
  },
};
